CREATE TABLE CUSTOMERS (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(50),
    Age NUMBER,
    Balance NUMBER,
    IsVIP CHAR(1)
);

CREATE TABLE LOANS(

    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    InterestRate NUMBER,
    DueDate DATE,

    FOREIGN KEY(CustomerID)
    REFERENCES CUSTOMERS(CustomerID)
);

-- insert values into CUSTOMER_TABLE
INSERT INTO CUSTOMERS
VALUES(1,'Rohit',65,15000,'N');

INSERT INTO CUSTOMERS
VALUES(2,'Rahul',45,8000,'N');

INSERT INTO CUSTOMERS
VALUES(3,'Aman',70,20000,'N');

INSERT INTO CUSTOMERS
VALUES(4,'Alia',58,12000,'N');

INSERT INTO CUSTOMERS
VALUES(5,'Radhika',62,9000,'N');

COMMIT;

